### ISSUE TITLE
12. Reservar vuelo

### ISSUE THREAD

**Issue by StivenHerreraSierra** [dpkg-i-foo-deb/Proyecto_Programacion_Avanzada#18]
## Descripción
Los usuarios registrados y que hayan reservado una o más habitaciones pueden realizar la reserva de un vuelo hacia esa ciudad.
Cada reserva de vuelo puede tener varios pasajeros. Los datos como ciudad de origen y destino, precio por silla y código de la reserva son tomados de la reserva de la/s habitacion/es.

## Actores
- Usuario registrado (cliente).

### Datos de entrada
- Fecha de reserva (NO la ingresa el usuario).
- Cantidad de pasajeros (sillas)
- Aerolínea.
- Usuario.

### Datos de salida
- Costo total pagado (Incluyendo el IVA).
- Reserva agregada al carrito de compras.

### Prueba 1
- Sólo está habilitado para usuarios registrados (NO incluye administradores).
- Sólo se puede reservar 1 vuelo por cada reserva de hotel.
- Se debe reservar por lo menos una silla.
- Si el usuario reserva un vuelo, su costo se debe sumar al valor total.

**Comment by dpkg-i-foo-deb** [comment]
- [ X ] Sólo se debe poder reservar un vuelo por reserva
