### ISSUE TITLE
17. Pausar publicación de hotel

### ISSUE THREAD

**Issue by StivenHerreraSierra** [dpkg-i-foo-deb/Proyecto_Programacion_Avanzada#23]
## Descripción
Los administradores de hotel pueden pausar la publicación de uno o más de sus hoteles registrados.
La pausa de la publicación no interfiere con las reservas ya confirmadas, sólo afecta las reservas que se realicen mientras se encuentra en este estado.

### Actores
- Administradores de hotel.

### Datos de entrada
- Hotel (código).
- Administrador de hotel (con esto se obtienen los hoteles que puede pausar).

### Datos de salida
- Retroalimentación del resultado de la operación.
- Cambios reflejados en la lista de sus hoteles registrados.

### Prueba 1
- Sólo los administradores de hotel puede pausar las publicaciones.
- Si un hotel está pausado no puede recibir solicitudes de reserva.

**Comment by dpkg-i-foo-deb** [comment]
Opción de pausar y reanudar agregada en 45d93ca52be76e96e745848bbe735928bb212c01

**Comment by dpkg-i-foo-deb** [comment]
Evitar que un hotel pausado sea reservado debería estar listo con: d381e8fd421179c0942a3117462e944575bbde5a

**Comment by dpkg-i-foo-deb** [comment]
Evitar que una habitación de un hotel que está pausado sea reservada ha sido garantizado con 86a401781be712eb032cb4161b39bfe13b4596ad
