### ISSUE TITLE
Solucionar el Problema de Ejecutar el Módulo Web

### ISSUE THREAD

**Issue by dpkg-i-foo-deb** [dpkg-i-foo-deb/Proyecto_Programacion_Avanzada#45]
Debe agregar  --add-opens java.base/java.lang=ALL-UNNAMED a las opciones de la máquina virtual si quiere ejecutar el módulo web, porque Java es todo raro

**Comment by StivenHerreraSierra** [comment]
El error se genera por la versión del JDK.

Más info: https://localcoder.org/how-to-fix-the-module-java-base-does-not-opens-java-io-to-unnamed-module
